/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";
import { useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Iphone17(props) {
  const { nodes, materials } = useGLTF("/models/IPHONE17.glb");
  const video = useVideoTexture("/textures/screen.mp4");

  // Fix the flipped orientation
  video.flipY = false;
  video.colorSpace = THREE.SRGBColorSpace;

  const texturedMaterial = new THREE.MeshStandardMaterial({
    map: video,
  });

  texturedMaterial.metalness = 0.1; // slight reflection
  texturedMaterial.roughness = 0.05; // smooth/glossy
  texturedMaterial.transparent = false;

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Phone" scale={46.64}>
          <group name="Back_Camera_module001">
            <mesh
              name="Cylinder004"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials["Metal Camera Frame"]}
            />
            <mesh
              name="Cylinder004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
            <mesh
              name="Cylinder004_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_2.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cylinder004_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_3.geometry}
              material={materials.Glass}
            />
            <mesh
              name="Cylinder004_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_4.geometry}
              material={materials["Metal Lens Frame"]}
            />
            <mesh
              name="Lens001"
              castShadow
              receiveShadow
              geometry={nodes.Lens001.geometry}
              material={materials["Glass Lens"]}
            />
          </group>
          <group name="Back_Camera_module002">
            <mesh
              name="Cylinder022"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022.geometry}
              material={materials["Metal Camera Frame"]}
            />
            <mesh
              name="Cylinder022_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
            <mesh
              name="Cylinder022_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_2.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cylinder022_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_3.geometry}
              material={materials.Glass}
            />
            <mesh
              name="Cylinder022_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_4.geometry}
              material={materials["Metal Lens Frame"]}
            />
            <mesh
              name="Lens002"
              castShadow
              receiveShadow
              geometry={nodes.Lens002.geometry}
              material={materials["Glass Lens"]}
            />
          </group>
          <group name="Back_Camera_module003">
            <mesh
              name="Cylinder026"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026.geometry}
              material={materials["Metal Camera Frame"]}
            />
            <mesh
              name="Cylinder026_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
            <mesh
              name="Cylinder026_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_2.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cylinder026_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_3.geometry}
              material={materials.Glass}
            />
            <mesh
              name="Cylinder026_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_4.geometry}
              material={materials["Metal Lens Frame"]}
            />
            <mesh
              name="Lens003"
              castShadow
              receiveShadow
              geometry={nodes.Lens003.geometry}
              material={materials["Glass Lens"]}
            />
          </group>
          <group name="Back_Flash">
            <mesh
              name="Esfera"
              castShadow
              receiveShadow
              geometry={nodes.Esfera.geometry}
              material={materials["Plastic Flash"]}
            />
            <mesh
              name="Esfera_1"
              castShadow
              receiveShadow
              geometry={nodes.Esfera_1.geometry}
              material={materials.LED}
            />
            <mesh
              name="Esfera_2"
              castShadow
              receiveShadow
              geometry={nodes.Esfera_2.geometry}
              material={materials["Plastic Flash Tint"]}
            />
          </group>
          <group name="Back_Glass">
            <mesh
              name="Cube010"
              castShadow
              receiveShadow
              geometry={nodes.Cube010.geometry}
              material={materials["Frosted Glass"]}
            />
            <mesh
              name="Cube010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube010_1.geometry}
              material={materials["Frosted Glass Tint"]}
            />
          </group>
          <mesh
            name="Back_Mic_mesh"
            castShadow
            receiveShadow
            geometry={nodes.Back_Mic_mesh.geometry}
            material={materials.Display}
          />
          <group name="Body">
            <mesh
              name="Cube001"
              castShadow
              receiveShadow
              geometry={nodes.Cube001.geometry}
              material={materials["Metal Body"]}
            />
            <mesh
              name="Cube001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_1.geometry}
              material={materials["Plastic Body Antena"]}
            />
            <mesh
              name="Cube001_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_2.geometry}
              material={materials.Metal}
            />
          </group>
          <mesh
            name="Button_Action"
            castShadow
            receiveShadow
            geometry={nodes.Button_Action.geometry}
            material={materials["Metal Body"]}
          />
          <mesh
            name="Button_Power_OnOff"
            castShadow
            receiveShadow
            geometry={nodes.Button_Power_OnOff.geometry}
            material={materials["Metal Body"]}
          />
          <mesh
            name="Button_Volume_Down"
            castShadow
            receiveShadow
            geometry={nodes.Button_Volume_Down.geometry}
            material={materials["Metal Body"]}
          />
          <mesh
            name="Button_Volume_Up"
            castShadow
            receiveShadow
            geometry={nodes.Button_Volume_Up.geometry}
            material={materials["Metal Body"]}
          />
          <group name="Camera_Control">
            <mesh
              name="Cube008"
              castShadow
              receiveShadow
              geometry={nodes.Cube008.geometry}
              material={materials.Metal}
            />
            <mesh
              name="Cube008_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube008_1.geometry}
              material={materials["Glass Camera Control"]}
            />
          </group>
          <group name="Front_Camera_module" position={[0.004, 0, 0.002]}>
            <mesh
              name="Cylinder025"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025.geometry}
              material={materials["Glass Lens"]}
            />
            <mesh
              name="Cylinder025_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
          </group>
          <mesh
            name="LIDAR"
            castShadow
            receiveShadow
            geometry={nodes.LIDAR.geometry}
            material={materials["Metal Lens Frame"]}
          />
          <mesh
            name="Screw"
            castShadow
            receiveShadow
            geometry={nodes.Screw.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Speaker_mesh"
            castShadow
            receiveShadow
            geometry={nodes.Speaker_mesh.geometry}
            material={materials.Display}
          />
          <mesh
            name="USB_C_port"
            castShadow
            receiveShadow
            geometry={nodes.USB_C_port.geometry}
            material={materials["Plastic Camera Frame"]}
          />
        </group>
        <mesh
          name="VIDEOTEXTURE"
          castShadow
          receiveShadow
          geometry={nodes.VIDEOTEXTURE.geometry}
          material={texturedMaterial}
          position={[0.018, 0.049, -0.009]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.708}
        />
        <mesh
          name="CAMERA"
          castShadow
          receiveShadow
          geometry={nodes.CAMERA.geometry}
          material={materials["Material.001"]}
          position={[0.108, 3.472, 0.213]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.605}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/IPHONE17.glb");
