/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Text, useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
export function Iphone(props) {
  const { nodes, materials } = useGLTF("./models/iphone.glb");

  const texture = useTexture("./IM/vaidya icon.png");

  // Fit texture fully
  texture.wrapS = THREE.ClampToEdgeWrapping;
  texture.wrapT = THREE.ClampToEdgeWrapping;
  texture.repeat.set(4, 4); // Default, full texture
  texture.offset.set(0, 0); // Align properly

  materials.Glass.map = texture;

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Phone">
          <group name="Back_Camera_module001">
            <mesh
              name="Cylinder004"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials["Metal Camera Frame"]}
            />
            <mesh
              name="Cylinder004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
            <mesh
              name="Cylinder004_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_2.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cylinder004_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_3.geometry}
              material={materials.Glass}
            />
            <mesh
              name="Cylinder004_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_4.geometry}
              material={materials["Metal Lens Frame"]}
            />
            <mesh
              name="Lens001"
              castShadow
              receiveShadow
              geometry={nodes.Lens001.geometry}
              material={materials["Glass Lens"]}
            />
          </group>
          <group name="Back_Camera_module002">
            <mesh
              name="Cylinder022"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022.geometry}
              material={materials["Metal Camera Frame"]}
            />
            <mesh
              name="Cylinder022_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
            <mesh
              name="Cylinder022_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_2.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cylinder022_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_3.geometry}
              material={materials.Glass}
            />
            <mesh
              name="Cylinder022_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder022_4.geometry}
              material={materials["Metal Lens Frame"]}
            />
            <mesh
              name="Lens002"
              castShadow
              receiveShadow
              geometry={nodes.Lens002.geometry}
              material={materials["Glass Lens"]}
            />
          </group>
          <group name="Back_Camera_module003">
            <mesh
              name="Cylinder026"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026.geometry}
              material={materials["Metal Camera Frame"]}
            />
            <mesh
              name="Cylinder026_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
            <mesh
              name="Cylinder026_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_2.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cylinder026_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_3.geometry}
              material={materials.Glass}
            />
            <mesh
              name="Cylinder026_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_4.geometry}
              material={materials["Metal Lens Frame"]}
            />
            <mesh
              name="Lens003"
              castShadow
              receiveShadow
              geometry={nodes.Lens003.geometry}
              material={materials["Glass Lens"]}
            />
          </group>
          <group name="Back_Flash">
            <mesh
              name="Esfera"
              castShadow
              receiveShadow
              geometry={nodes.Esfera.geometry}
              material={materials["Plastic Flash"]}
            />
            <mesh
              name="Esfera_1"
              castShadow
              receiveShadow
              geometry={nodes.Esfera_1.geometry}
              material={materials.LED}
            />
            <mesh
              name="Esfera_2"
              castShadow
              receiveShadow
              geometry={nodes.Esfera_2.geometry}
              material={materials["Plastic Flash Tint"]}
            />
          </group>
          <group name="Back_Glass">
            <mesh
              name="Cube010"
              castShadow
              receiveShadow
              geometry={nodes.Cube010.geometry}
              material={materials["Frosted Glass"]}
            />
            <mesh
              name="Cube010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube010_1.geometry}
              material={materials["Frosted Glass Tint"]}
            />
          </group>
          <mesh
            name="Back_Mic_mesh"
            castShadow
            receiveShadow
            geometry={nodes.Back_Mic_mesh.geometry}
            material={materials.Display}
          />
          <group name="Body">
            <mesh
              name="Cube"
              castShadow
              receiveShadow
              geometry={nodes.Cube.geometry}
              material={materials["Metal Body"]}
            />
            <mesh
              name="Cube_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube_1.geometry}
              material={materials["Plastic Body Antena"]}
            />
            <mesh
              name="Cube_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube_2.geometry}
              material={materials.Metal}
            />
          </group>
          <mesh
            name="Button_Action"
            castShadow
            receiveShadow
            geometry={nodes.Button_Action.geometry}
            material={materials["Metal Body"]}
          />
          <mesh
            name="Button_Power_OnOff"
            castShadow
            receiveShadow
            geometry={nodes.Button_Power_OnOff.geometry}
            material={materials["Metal Body"]}
          />
          <mesh
            name="Button_Volume_Down"
            castShadow
            receiveShadow
            geometry={nodes.Button_Volume_Down.geometry}
            material={materials["Metal Body"]}
          />
          <mesh
            name="Button_Volume_Up"
            castShadow
            receiveShadow
            geometry={nodes.Button_Volume_Up.geometry}
            material={materials["Metal Body"]}
          />
          <group name="Camera_Control">
            <mesh
              name="Cube008"
              castShadow
              receiveShadow
              geometry={nodes.Cube008.geometry}
              material={materials.Metal}
            />
            <mesh
              name="Cube008_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube008_1.geometry}
              material={materials["Glass Camera Control"]}
            />
          </group>
          <group name="Front_Camera_module">
            <mesh
              name="Cylinder025"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025.geometry}
              material={materials["Glass Lens"]}
            />
            <mesh
              name="Cylinder025_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025_1.geometry}
              material={materials["Plastic Camera Frame"]}
            />
          </group>
          <mesh
            name="LIDAR"
            castShadow
            receiveShadow
            geometry={nodes.LIDAR.geometry}
            material={materials["Metal Lens Frame"]}
          />
          <group name="Screen">
            <mesh
              name="Cube006"
              castShadow
              receiveShadow
              geometry={nodes.Cube006.geometry}
              material={materials["Glass Tint"]}
            />
            <mesh
              name="Cube006_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube006_1.geometry}
              material={materials.Display}
            />
            <mesh
              name="Cube006_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube006_2.geometry}
              material={materials.Glass}
            >
              <mesh geometry={nodes.Cube006_2.geometry}>
                <meshBasicMaterial map={texture} />
              </mesh>
            </mesh>
          </group>
          <mesh
            name="Screw"
            castShadow
            receiveShadow
            geometry={nodes.Screw.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Speaker_mesh"
            castShadow
            receiveShadow
            geometry={nodes.Speaker_mesh.geometry}
            material={materials.Display}
          />
          <mesh
            name="USB_C_port"
            castShadow
            receiveShadow
            geometry={nodes.USB_C_port.geometry}
            material={materials["Plastic Camera Frame"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/iphone.glb");
