import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page";
import Header from "./Header/page";
import SmoothScroll from "@/components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vaidya 247",
  description: "Generated by VAIDYA",
  icons: {
    icon: "/public/vaidya.png",
    shortcut: "/public/vaidya.png",
    apple: "/public/vaidya.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/public/vaidya.png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
        <Footer />
      </body>
    </html>
  );
}
